[application]

default_platform = "desktop"

# HTML title tag content
title = "Wuthering Waves FPS Unlocker"

# include `assets` in web platform
[web.resource]

# Additional CSS style files
style = []

# Additional JavaScript files
script = []

[web.resource.dev]

# Javascript code file
# serve: [dev-server] only
script = []


[bundle]
identifier = "com.peekaey"
publisher = "Peekaey"
icon = ["assets/wuwa-icon.png"]
